"""Alembic environment.

The connection string is read from ``DATABASE_URL`` rather than alembic.ini, so
no credential is ever written to a file that git tracks.

Migrations here are hand-written SQL rather than autogenerated from ORM models.
That is deliberate: this schema's security properties live in GRANTs, row-level
security policies and append-only triggers, none of which an ORM model captures.
The SQL is the specification, and it has to be reviewable as SQL by people who
are checking our compliance claims.
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        sys.exit(
            "DATABASE_URL is not set.\n"
            "  local dev: postgresql+psycopg://pps:pps@localhost:5432/pps\n"
            "  deployed:  read it from AWS Secrets Manager, never from a file in git"
        )
    return url


# No ORM metadata: every migration is explicit SQL, so autogenerate is not used.
target_metadata = None


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it.

    This is how a reviewer or a DBA sees exactly what will hit production
    before it does: ``alembic upgrade head --sql``.
    """
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    config.set_main_option("sqlalchemy.url", _database_url())
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
