/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#a9cbe5',
        'inverse-on-surface': '#eff1f5',
        'tertiary-fixed-dim': '#a0d2b3',
        'on-primary-fixed-variant': '#284a60',
        'on-secondary-fixed': '#001e2f',
        'on-tertiary-fixed-variant': '#204f38',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#abcae4',
        'secondary-fixed': '#c8e6ff',
        'surface-container-low': '#f2f3f7',
        'on-secondary-container': '#47667d',
        'on-secondary-fixed-variant': '#2b4a5f',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e7e8ec',
        'on-surface-variant': '#42474c',
        'secondary': '#436278',
        'tertiary': '#2a5841',
        'on-primary-container': '#d0eaff',
        'on-error': '#ffffff',
        'tertiary-container': '#427158',
        'background': '#f8f9fd',
        'inverse-surface': '#2e3134',
        'outline': '#72787d',
        'primary': '#315369',
        'surface-dim': '#d8dade',
        'surface-container-highest': '#e1e2e6',
        'on-tertiary-fixed': '#002112',
        'tertiary-fixed': '#bbeecf',
        'surface-tint': '#416279',
        'on-tertiary-container': '#c0f3d3',
        'on-surface': '#191c1f',
        'on-primary': '#ffffff',
        'surface-container': '#eceef2',
        'primary-container': '#4a6b82',
        'primary-fixed': '#c8e6ff',
        'surface-bright': '#f8f9fd',
        'error': '#ba1a1a',
        'surface-variant': '#e1e2e6',
        'on-background': '#191c1f',
        'primary-fixed-dim': '#a9cbe5',
        'secondary-container': '#c3e4fe',
        'surface': '#f8f9fd',
        'outline-variant': '#c2c7cd',
        'on-primary-fixed': '#001e2e'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'margin': '3rem',
        'gutter': '1.5rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.25rem'
      },
      fontFamily: {
        'headline-sm': ['Newsreader', 'Georgia', 'serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Newsreader', 'Georgia', 'serif'],
        'display-lg': ['Newsreader', 'Georgia', 'serif'],
        'metric-display': ['Inter', 'sans-serif'],
        'headline-lg': ['Newsreader', 'Georgia', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Newsreader', 'Georgia', 'serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Newsreader', 'Georgia', 'serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Newsreader', 'Georgia', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'serif': ['Newsreader', 'Georgia', 'serif'],
        'sans': ['Inter', 'sans-serif']
      },
      fontSize: {
        'headline-sm': ['1.25rem', { 'lineHeight': '1.75rem', 'fontWeight': '500' }],
        'title-sm': ['1rem', { 'lineHeight': '1.5rem', 'fontWeight': '600' }],
        'label-sm': ['0.75rem', { 'lineHeight': '1rem', 'fontWeight': '500' }],
        'headline-md': ['1.5rem', { 'lineHeight': '2rem', 'fontWeight': '500' }],
        'display-lg': ['3rem', { 'lineHeight': '3.5rem', 'fontWeight': '400' }],
        'metric-display': ['2rem', { 'lineHeight': '2.25rem', 'fontWeight': '600' }],
        'headline-lg': ['2rem', { 'lineHeight': '2.5rem', 'fontWeight': '400' }],
        'body-md': ['0.9375rem', { 'lineHeight': '1.5rem', 'fontWeight': '400' }],
        'headline-lg-mobile': ['1.625rem', { 'lineHeight': '2.125rem', 'fontWeight': '400' }],
        'title-md': ['1.125rem', { 'lineHeight': '1.625rem', 'fontWeight': '600' }],
        'body-lg': ['1.125rem', { 'lineHeight': '1.75rem', 'fontWeight': '400' }],
        'body-sm': ['0.8125rem', { 'lineHeight': '1.25rem', 'fontWeight': '400' }],
        'display-lg-mobile': ['2.25rem', { 'lineHeight': '2.75rem', 'fontWeight': '400' }],
        'label-md': ['0.8125rem', { 'lineHeight': '1.125rem', 'fontWeight': '600' }]
      }
    }
  },
  plugins: [],
}
